#pragma config(Sensor, in1,    hyro,           sensorGyro)
#pragma config(Sensor, in2,    shoulderPot,     sensorPotentiometer)
#pragma config(Sensor, in3,    wristPot,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEnc,       sensorQuadEncoder)
#pragma config(Motor,  port1,           rbd,           tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           lbd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lfd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rfd,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           shoulder1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           shoulder2,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           wrist1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           wrist2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           claw1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          claw2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

int wristPower = 100; //<--- Change this

#include "buttonTracker.c"
#include "parallelDrive.c"
#include "pd_autoMove.c"
#include "motorGroup.c"

//buttons
#define openClawBtn Btn6D //claw
#define closeClawBtn Btn6U
#define toggleLiftModeBtn Btn8U //lift
#define shoulderUpBtn Btn5U
#define shoulderDownBtn Btn5D
#define wristUpBtn Btn7U
#define wristDownBtn Btn7D

//positions
#define shoulderIntercept -52.566 //angles at potentiometerVal==0
#define wristIntercept -136.29

//constants
#define angleRegressionSlope .0651 //degrees per potentiometer value
#define shoulderStillSpeed 10 //still speeds
#define wristStillSpeed 5
#define clawStillSpeed 15

short clawSign = -1; //Sign of still speed. Positive if closed, negative if open
bool fourBar = false; //whether lift is in dumper of four bar mode
float targetAngle = 0; //claw-to-ground angle maintained during 4-bar mode

motorGroup shoulder;
motorGroup wrist;
motorGroup claw;

float liftAngle(bool wrist=true, bool relative=false) {
	if (wrist) {
		float wristAngle = angleRegressionSlope*potentiometerVal(wrist) + wristIntercept;

		if (relative) {
			return wristAngle;
		} else {
			return wristAngle + liftAngle(false);
		}
	} else {
		return angleRegressionSlope*potentiometerVal(shoulder) + shoulderIntercept;
	}
}

//autonomous region
void pre_auton() {
	bStopTasksBetweenModes = true;

	initializeDrive(drive);
  setDriveMotors(drive, 4, lfd, lbd, rfd, rbd);
  attachEncoder(drive, leftEnc, LEFT);
  attachEncoder(drive, rightEnc, RIGHT, true, 4);
  attachGyro(drive, hyro);

  initializeGroup(shoulder, 2, shoulder1, shoulder2);
  configureButtonInput(shoulder, liftUpBtn, liftDownBtn, liftStillSpeed);
  addSensor(shoulder, shoulderPot, true);

	initializeGroup(wrist, 2, wrist1, wrist2);
	configureButtonInput(wrist, Btn7U, Btn7D);
	addSensor(wrist, wristPot);

  initializeGroup(claw, 2, claw1, claw2);
}

task autonomous() {
  turn(-45);
	driveStraight(3*12*sqrt(2));
	turn(-135, defTurnInts[0], defTurnInts[1], -40);
	driveStraight(3*12);
}
//end autonomous region

void switchLiftMode() {
	fourBar = !fourBar;

	if (fourBar)
		targetAngle = liftAngle();
}

//user control region
void liftControl() {
	if (newlyPressed(toggleLiftModeBtn))
		switchLiftMode();

	shoulder.stillSpeed = shoulderStillSpeed * (potentiometerVal(shoulder)>liftMiddle ? 1 : -1);
	short shoulderPower = takeInput(shoulder);
	short wristPower = takeInput(wrist, false);

	if (wristPower != 0) {
		setPower(wrist, wristPower);
	}	else if (shoulderPower == liftStillSpeed) {
		setPower(wrist, wristStillSpeed);
	} else {
		int targetPos =
		setPower(wrist, (fourBar ? shoulderPower*wristPower/127 : -wristStillSpeed);
	}
}

void clawControl() {
	if (vexRT[closeClawBtn] == 1) {
		setPower(claw, 127);
		clawSign = 1;
	} else if (vexRT[openClawBtn] == 1) {
		setPower(claw, -127);
		clawSign = -1;
	} else {
		setPower(claw, clawStillSpeed * clawSign);
	}
}

task usercontrol() {
	while (true) {
  	driveRuntime(drive);

  	liftControl();

		clawControl();

		if (vexRT[Btn7U] == 1) autoTest();
  }
}
//end user control region
